database/migrations/2023_01_16_000001_create_customers_table.php, database/migrations/2023_01_16_000002_create_subscriptions_table.php
Hello,
I am aware that the use of "down" methods in our migrations is typically [unnecessary](https://laraveldaily.com/post/still-need-migrations-taylor-says-no) these days. However, it is still considered standard practice in Laravel, isn't it? With that in mind, I have submitted a pull request to include it.
Thank you for your great work, 
George
=> Add "down" method for migrations

README.md
I could not find the ID in the "General" Settings but found it in the "Stores" settings.
=> Change URL to find lmnsqueezy store ID in README.md

README.md, src/Checkout.php, src/Concerns/ManagesCheckouts.php
This will add support for custom price during the checkout by providing the `custom_price` key to options array.
=> Add support for custom price at checkout

src/Http/Controllers/WebhookController.php
I want to listen to the `SubscriptionPaymentSuccess`, `SubscriptionPaymentFailed`, and `SubscriptionPaymentRecovered` events. Still, it does not work, the `$this->findSubscription($payload['data']['id'])` always returns `null`, then I look at my webhooks records and see the `SubscriptionPaymentSuccess` event's `data.attributes.subscription_id` same as my database's Subscription `lemon_squeezy_id`, so this PR is to fix this.
The `SubscriptionPaymentSuccess`, `SubscriptionPaymentFailed` and `SubscriptionPaymentRecovered` events both are **Subscription Invoice object** in [**Webhooks Event types**](https://docs.lemonsqueezy.com/help/webhooks#event-types):
And trace to [**Subscription Invoice object**](https://docs.lemonsqueezy.com/api/subscription-invoices#the-subscription-invoice-object) …
=> Fix can't find Subscription from SubscriptionPayment

README.md, src/Checkout.php
This will add support for custom name and decription during the checkout by providing the $productName and $description.
name - A custom name for the product
description - A custom description for the product
receipt_thank_you_note - A custom thank you note to use for the order receipt email
And still didnt get to know how to make this receipt_thank_you_note work.
Do you have any suggestion how make this work?
=> Add support for custom name, description at checkout. And receipt_thank_you_note.

src/Http/Controllers/WebhookController.php
The `OrderRefunded` event was being called on the licenseCreated method on the webhook controller
=> Dispatching the correct event name when a license is created

src/Http/Middleware/VerifyWebhookSignature.php
The use of `!==` over `hash_equals` was bothering me, not sure if the validation needs a timing-safe string comparison but better safe than sorry. It is also the way Lemon Squeezy uses in [their example](https://docs.lemonsqueezy.com/guides/developer-guide/webhooks#signing-and-validating-webhook-requests):
```php
$secret    = '[SIGNING_SECRET]'; // from your webhook settings
$payload   = file_get_contents('php://input');
$hash      = hash_hmac('sha256', $payload, $secret);
$signature = $_SERVER['HTTP_X_SIGNATURE'] ?? '';
if (!hash_equals($hash, $signature)) {
throw new Exception('Invalid signature.');
}
```
=> Use `hash_equals` when validating webhook signature

README.md
Removed extra preposition from a sentence.
Before: `If you're checking out subscriptions, and you don't want **to to** show the "You will be charged..." text, you may disable this by calling the `withoutSubscriptionPreview` method on the checkout object:`
After: `If you're checking out subscriptions, and you don't want **to** show the "You will be charged..." text, you may disable this by calling the `withoutSubscriptionPreview` method on the checkout object:`
=> Grammer typo: Wrong preposition 

src/Http/Controllers/WebhookController.php
Hi there!
I've encountered a small issue in my app.
During user registration, I initiate a generic trial with:
```php
$user->createAsCustomer([
'trial_ends_at' => now()->addDays(7)->endOfDay(),
]);
```
After this process, the Customer appears as follows:
```php
LemonSqueezy\Laravel\Customer {#2544
id: 9,
billable_id: 16,
billable_type: "App\Models\User",
lemon_squeezy_id: null,
trial_ends_at: "2023-11-07 23:59:59",
created_at: "2023-10-31 18:29:25",
updated_at: "2023-10-31 18:29:25",
}
```
When a user decides to subscribe, the app receives webhooks from Lemon Squeezy. One of these events is `subscription_created` which sets `trial_ends_at` to `null` but didn't update `lemon_squeezy_id`.
=> Fix missing lemon_squeezy_id if billable was on generic trial

database/migrations/2023_01_16_000003_create_orders_table.php, src/Concerns/ManagesOrders.php, src/Http/Controllers/WebhookController.php, src/Order.php
This PR contains the following fixes:
* The fix from #61 (changing `static::` to `Order::`)
* Populate the the `identifier` field from the payload
* I was getting a db error because it was never filled from the webhook handler
* Making `tax_name` a nullable field because it was coming back "null" for me
* Retrieving order details from `$payload['data']['attributes']['first_order_item']`
* Not sure if this is the right way, but it's the only thing in my webhook payload that contained "product_id" and "variant_id"
* Maybe the payloads are different if the product has a variant or not, but in my case, I can't create a "checkout" link without a variant, so I had to create a variant
I didn't add any tests because there's no precedent for webhook tests. Might be something to consider: tests …
=> Fix order webhook handler

src/Order.php
The Order model is missing an import for the `Illuminate\Database\Eloquent\Builder`, which causes the scopes to fail with the error: `Argument #1 ($query) must be of type LemonSqueezy\Laravel\Builder, Illuminate\Database\Eloquent\Builder given`
This PR adds the missing import.
=> fix: Missing Illuminate Builder import in Order model

src/Console/ListenCommand.php
Handles when `LEMON_SQUEEZY_SIGNING_SECRET` is not set in the env, by falling back to a hash of the `LEMON_SQUEEZY_API_KEY`
=> Closes #77 Listen command throws error

src/Console/ListenCommand.php, tests/Feature/Commands/ListenCommandTest.php, tests/TestCase.php
This PR fixes the following issues:
1. Exit Codes were not being properly reported to GitHub Actions due to exit() calls on a command execute from the tests
2. Changes to TestCase to execute Laravel migrations on Laravel 11
=> Fix Tests on Laravel 11 and exit codes

src/Concerns/ManagesSubscriptions.php
If I set CarbonImmutable as default carbon instance via `Date::use(CarbonImmutable::class);` in my AppServiceProvider, I get an return type error for trialEndsAt. This PR fixes that.
=> Replace carbon return type with carboninterface for trialEndsAt

README.md, src/Console/ListProductsCommand.php, src/LemonSqueezyServiceProvider.php, tests/Feature/Commands/ListProductsCommandTest.php
This Pull Request introduces the following changes:
1. New Command that can query the Lemon Squeezy API for products and variants;
2. Command can list all products and their variants or an argument can also be passed to query the variants of a specific product;
**Note:** The products query can only show 100 products since I am doing only 1 request to the endpoint using a page size of 100 (maximum), can be changed to do a recursive request to show 100, I just was thinking if It makes sense to show so many products or a message with a link to the Lemon Squeezy Dashboard.
I think at some point we should introduce a class to query products and variants as it would be nice to make that affordance available for users to query the products and variants from Lemon Squeezy, maybe even import them …
=> Add command to list products and variants

src/Console/ListProductsCommand.php, tests/Feature/Commands/ListProductsCommandTest.php
When you have more than one store, the products where not shown correctly.
I've fixed it, now the correct products are shown based on the set store.
=> fix: Filter correct products for store in ListProductsCommand

src/Console/ListenCommand.php
Removed annoying "Remaining time:"  empty lines from terminal when running expose.
Before: 
After:
=> fix: clean up annoying empty lines and timer for expose listen in terminal

README.md, src/Console/ListLicensesCommand.php, src/LemonSqueezyServiceProvider.php, tests/Feature/Commands/ListLicensesCommandTest.php
Supports filtering on:
- Product
- Order
- Status
Supports showing full or shorthand license key. I've also added pagination to this command as there's probably large amounts of purchased licenses for all available products. I'm working on the broader license key functionality including license activation. PR for that will follow soon.
=> Create list licenses console command

src/Console/ListLicensesCommand.php
Fix deprecated variable syntax from `${var}` to `{$var}` for PHP 8.4+.
Addresses #118
=> Fix deprecated variable syntax

README.md, database/factories/LicenseKeyFactory.php, database/migrations/2023_01_16_000004_create_license_keys_table.php, database/migrations/2023_01_16_000005_create_license_key_instances_table.php, src/Billable.php, src/Concerns/ManagesLicenses.php, src/Events/LicenseKeyCreated.php, src/Events/LicenseKeyUpdated.php, src/Exceptions/InvalidCustomPayload.php, src/Exceptions/LicenseKeyNotFound.php, src/Exceptions/LicenseKeyNotValidated.php, src/Exceptions/MalformedDataError.php, src/Exceptions/ReservedCustomKeys.php, src/Http/Controllers/WebhookController.php, src/Http/Throwable/BadRequest.php, src/Http/Throwable/NotFound.php, src/LicenseKey.php, src/LicenseKeyInstance.php, tests/Feature/LicenseTest.php
Sorry this took me a while! This PR introduces the license keys feature, including two new migrations for license keys and license key instances.
It introduces a new trait with billable methods for activating and validating a license key, and handles the events related to license keys.
I ran into some snags re: the ngrok listen command so a PR for that may or may not follow depending on how swamped I get :sweat_smile: LMK if there's any questions
=> Creates the license key feature

composer.json
This PR should fix issue: #132.  I think we forgot to be bumping the versions. packagist completely ignored the 1.8.3 and 1.8.4 releases. The composer docs recommends we should omit it completely and let composer infer the version from the release tags. which is better? https://getcomposer.org/doc/04-schema.md#version
=> chore: bumping package version to 1.8.4 in composer.json

src/Console/ListenCommand.php
This pull request includes a small change to the `src/Console/ListenCommand.php` file. The change improves the handling of the `Date` header in the `ngrok` function by adding a check to see if the `Date` header is set before attempting to parse it.
* [`src/Console/ListenCommand.php`](diffhunk://#diff-070ddc3a61bc9c230ffacaef353905639b9f624664c4210fbf2cbc7aeaca4c6cL292-R294): Added a check to ensure the `Date` header is set before parsing it, and provided a default value of `[Date-Not-Set]` if it is not present.
=> fix: fixing #139
